[package]
name = "computertest"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.1"
rand = "0.8"
env_logger = "0.11.5"
log = "0.4.22"
chrono = "0.4.38"